CREATE TABLE Raw_CountStunting(District_Name VARCHAR, "Tidak Stunting" BIGINT, Stunting BIGINT);;
INSERT INTO Raw_CountStunting VALUES('BENUKI',18,33);
INSERT INTO Raw_CountStunting VALUES('MAMBERAMO HILIR',45,20);
INSERT INTO Raw_CountStunting VALUES('MAMBERAMO HULU',28,7);
INSERT INTO Raw_CountStunting VALUES('MAMBERAMO TENGAH',104,16);
INSERT INTO Raw_CountStunting VALUES('MAMBERAMO TENGAH TIMUR',16,3);
INSERT INTO Raw_CountStunting VALUES('SAWAI',34,107);
INSERT INTO Raw_CountStunting VALUES('WAROPEN ATAS',34,142);
